name: CI/CD Pipeline
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Iniciar la app (prueba básica)
        run: python -c "from app import app; print('¡App funciona correctamente!')"
      - name: Desplegar
        run: echo "Aquí irían tus comandos de despliegue reales"
